# Generated by Django 3.2.13 on 2022-04-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=100)),
                ('meters', models.CharField(max_length=100)),
                ('meters_corrections', models.CharField(max_length=100)),
                ('date_of_creation', models.DateField(blank=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_height', models.FloatField()),
                ('sighting_points', models.CharField(max_length=100)),
                ('gorizontal_angle_gradus', models.IntegerField()),
                ('gorizontal_angle_min', models.FloatField()),
                ('sighting_points_neighbors', models.IntegerField()),
                ('sighting_points_neighbors_height', models.FloatField()),
                ('vertical_angle_gradus', models.IntegerField()),
                ('vertical_angle_min', models.FloatField()),
                ('rail', models.FloatField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tah.journal')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
