# Generated by Django 3.2.13 on 2022-04-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tah', '0003_journal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='gorizontal_angle_gradus',
            new_name='gorizontal_angle_gradus1',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='sighting_points_neighbors',
            new_name='gorizontal_angle_gradus2',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='vertical_angle_gradus',
            new_name='gorizontal_angle_gradus3',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='gorizontal_angle_min',
            new_name='gorizontal_angle_min1',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='rail',
            new_name='gorizontal_angle_min2',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='sighting_points_neighbors_height',
            new_name='gorizontal_angle_min3',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='vertical_angle_min',
            new_name='gorizontal_angle_min4',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='sighting_points',
            new_name='rail1',
        ),
        migrations.AddField(
            model_name='station',
            name='gorizontal_angle_gradus4',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='rail2',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='rail3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='rail4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points1',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points2',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points3',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points4',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points_neighbors1',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points_neighbors2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points_neighbors_height1',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='sighting_points_neighbors_height2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_gradus1',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_gradus2',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_gradus3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_gradus4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_min1',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_min2',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_min3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='vertical_angle_min4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
